#!/bin/bash

# Notice.
echo "Before installing, make sure"
echo
echo "(1) your OS dispose of a bash shell (eg. Linux, Mac, Unix, Solaris, HP),"
echo "(2) your internet connection is working properly,"
echo "(3) your R satisfies packages dependencies,"
echo "(4) a working installation of PostgreSQL is up and running accessible from command line with no parameters."
echo 
echo -n "Proceed? [y/N] "
read -n 1 proceed
echo

if [ "${proceed}" != "y" ]
then
  exit
fi

# R packages download.
for i in $(grep -R "library(" include/* | grep -v "libraries.R" | cut -d":" -f 2 | cut -d "'" -f 2)
do
  echo $i
  R -q --vanilla <<EOF
install.packages("$i")
EOF
done

# Database creation.
echo "CREATE DATABASE clarity;" | psql

# Symbols downloading.
echo "Downloading indicators and instruments..."
cd data-providers
for i in $(cat quantmod.txt); do sh quantmod-download "$i"; done
for i in $(cat quandl.txt); do sh quandl-download "$i"; done
cd ..

# Create temp dir.
mkdir tmp

# Success.
rootdir=$(pwd)
echo "Clarity should be up and running now. Start off by running any example out of 'examples' dir inside your RStudio."
echo "Noteworthy, if you plan to use Clarity outside RStudio, please set ${rootdir} as your root dir with setwd();"
