#!/bin/bash

# defina o número de vértices do grafo
VERTICES=13

# para definir a média e desvio padrão, ajuste as variáveis
# no script gerado automaticamente em script.R, logo abaixo.

cat > script.R << EOF
# número de vértices do grafo
num_vertices <- $VERTICES

# parâmetros da distribuição normal
media <- 1
desvio_padrao <- 0.1
margem <- 0.000

n <- num_vertices
m <- matrix(, nrow=n, ncol=n)
for (i in 1:n)
  for (j in 1:n) {
    if (i > j)
      m[i,j] <- rnorm(1, media, desvio_padrao)[1]
    else if (i == j)
      m[i,j] <- 0
  }

for (i in 1:n)
  for (j in 1:n)
    if (i < j)
      m[i,j] <- rnorm(1, 1/m[j,i], margem)[1]

final <- matrix(, nrow=n, ncol=n-1)
for (i in 1:n)
  for (j in 1:(i-1))
    final[i, j] <- m[i, j]

for (i in 1:n) {
  if (i < n)
    espaco <- seq(from=i, to=n-1, by=1)
  else
    espaco <- c()
  for (j in espaco)
    final[i,j] <- m[i,j+1]
}

write(n, file="teste")
write.table(final, file="teste", row.names=FALSE, col.names=FALSE)
EOF
cat > grafo_aleatorio <<EOF
$VERTICES
EOF
R --file=script.R --no-save --slave
cat >> grafo_aleatorio < teste
rm teste script.R
